# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86a06bf5c2bdfd7879024cac63d7b4e5a6be98fdef5728459c73241c57f15b43806de07845d49a352ecad033675b055890fad1aa7e2e0ba51ef61a4fd164b249

test:
  secret_key_base: 873663b1c6993ae852217744b6375422d9905f953e6d1872e2492028889c33873c7c665f9555cdd4f06c2036b98a330d23abd33ed37fc7c393083faf7f6dcd52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
